defmodule AssessmentApi.Web.Types do
  use Absinthe.Schema.Notation

  import_types(AssessmentApi.Web.Schema.Domain.Choice)
  import_types(AssessmentApi.Web.Schema.Domain.Classroom)
  import_types(AssessmentApi.Web.Schema.Domain.Grade)
  import_types(AssessmentApi.Web.Schema.Domain.MultipleChoice)
  import_types(AssessmentApi.Web.Schema.Domain.MultipleChoiceQuestion)
  import_types(AssessmentApi.Web.Schema.Domain.LongAnswerQuestion)
  import_types(AssessmentApi.Web.Schema.Domain.TrueFalseQuestion)
  import_types(AssessmentApi.Web.Schema.Domain.FillInTheBlankQuestion)
  import_types(AssessmentApi.Web.Schema.Domain.QuestionBase)
  import_types(AssessmentApi.Web.Schema.Domain.Question)
  import_types(AssessmentApi.Web.Schema.Domain.Objective)
  import_types(AssessmentApi.Web.Schema.Domain.Question)
  import_types(AssessmentApi.Web.Schema.Domain.QuestionAnswerKey)
  import_types(AssessmentApi.Web.Schema.Domain.Stimulus)
  import_types(AssessmentApi.Web.Schema.Domain.Student)
  import_types(AssessmentApi.Web.Schema.Domain.StudentAnswerKey)
  import_types(AssessmentApi.Web.Schema.Domain.StudentQuestion)
  import_types(AssessmentApi.Web.Schema.Domain.StudentTest)
  import_types(AssessmentApi.Web.Schema.Domain.Teacher)
  import_types(AssessmentApi.Web.Schema.Domain.Test)
  import_types(AssessmentApi.Web.Schema.Domain.User)
  import_types(AssessmentApi.Web.Schema.Domain.TestAnalytics)
  import_types(AssessmentApi.Web.Schema.Domain.StudentTestAnalytics)
  import_types(AssessmentApi.Web.Schema.Domain.ObjectiveAnalytics)
  import_types(AssessmentApi.Web.Schema.Domain.AnswerKeyAnalytics)
end
